services:
  xttsapiserver:
    env_file: .env
    build:
      context: ..
      dockerfile: ./docker/cpu.Dockerfile
    ports:
      - "${HOST_PORT:-8020}:${CONTAINER_PORT:-8020}"
    volumes:
      - ./xtts-server:/xtts-server
